### ISSUE TITLE
Decompile_all gets stuck after antigravity

### ISSUE THREAD

**Issue by ChariseWalraven** [andrew-tavera/unpyc37#11]
Hi there, I've cloned the latest version of this repo, but the decompile_all script hangs after it gets to the antigravity module. 

I'm running python version 3.7. I'm on a Windows 10 Pro Asus laptop

I initially tried using the version that comes with the Anaconda installer, but also tried using the version that you can download from the python website [as specified in this tutorial](http://sims4studio.com/thread/15145/started-python-scripting-updated).

The output basically just hangs once  it gets to `EA\base\lib\antigravity.pyc`

Please let me know what other info you need.

**Comment by ChariseWalraven** [comment]
I've traced the issue to the commit aa1b0c4 from May 14th 2019. There's a while loop that never breaks, I think. I'm not really all that familiar with Python, so I don't think I'll be much help fixing it, and since I don't have any failed extractions or anything from the commit before, this isn't breaking anything for me (yet). But I think if I'm experiencing this issue, others must be, too. Any fixes would be appreciated. :)

Let me know if there's anything you think I can do to help.

**Comment by andrew-tavera** [comment]
Hi ChariseWalraven, 
I have just pushed the latest changes to this project. It is still not perfect, but should be more accurate than it was before and not hang while decompiling. Let me know if it is still hanging on any pyc :).

**Comment by ChariseWalraven** [comment]
Hi Andrew,

Thank you very much! I'll take a look when I am able.
