### ISSUE TITLE
Two-argument assert is missing 2nd (message string) argument in decompilation

### ISSUE THREAD

**Issue by rocky** [andrew-tavera/unpyc37#7]

**Comment by rocky** [comment]
```python
assert __name__, "Your Python is normal"
```

when compiled and decompled loses the message field. That is, it comes back: 

```python
assert __name__
```

**Comment by andrew-tavera** [comment]
Thanks rocky, this should be fixed now in 2ea8cbe07d92396f18433d445fe795f96af36bfa

**Comment by rocky** [comment]
Yes indeed. This code is looking pretty good!
